Public Class TipoCambio
    Public Property IdTipoCambio As Int32
    Public Property IdMoneda As Int32
    Public Property Anio As Int32
    Public Property Mes As Int32
    Public Property CompraCierre As Decimal
    Public Property VentaCierre As Decimal
    Public Property Compra1 As Decimal
    Public Property Compra2 As Decimal
    Public Property Compra3 As Decimal
    Public Property Compra4 As Decimal
    Public Property Compra5 As Decimal
    Public Property Compra6 As Decimal
    Public Property Compra7 As Decimal
    Public Property Compra8 As Decimal
    Public Property Compra9 As Decimal
    Public Property Compra10 As Decimal
    Public Property Compra11 As Decimal
    Public Property Compra12 As Decimal
    Public Property Compra13 As Decimal
    Public Property Compra14 As Decimal
    Public Property Compra15 As Decimal
    Public Property Compra16 As Decimal
    Public Property Compra17 As Decimal
    Public Property Compra18 As Decimal
    Public Property Compra19 As Decimal
    Public Property Compra20 As Decimal
    Public Property Compra21 As Decimal
    Public Property Compra22 As Decimal
    Public Property Compra23 As Decimal
    Public Property Compra24 As Decimal
    Public Property Compra25 As Decimal
    Public Property Compra26 As Decimal
    Public Property Compra27 As Decimal
    Public Property Compra28 As Decimal
    Public Property Compra29 As Decimal
    Public Property Compra30 As Decimal
    Public Property Compra31 As Decimal
    Public Property Venta1 As Decimal
    Public Property Venta2 As Decimal
    Public Property Venta3 As Decimal
    Public Property Venta4 As Decimal
    Public Property Venta5 As Decimal
    Public Property Venta6 As Decimal
    Public Property Venta7 As Decimal
    Public Property Venta8 As Decimal
    Public Property Venta9 As Decimal
    Public Property Venta10 As Decimal
    Public Property Venta11 As Decimal
    Public Property Venta12 As Decimal
    Public Property Venta13 As Decimal
    Public Property Venta14 As Decimal
    Public Property Venta15 As Decimal
    Public Property Venta16 As Decimal
    Public Property Venta17 As Decimal
    Public Property Venta18 As Decimal
    Public Property Venta19 As Decimal
    Public Property Venta20 As Decimal
    Public Property Venta21 As Decimal
    Public Property Venta22 As Decimal
    Public Property Venta23 As Decimal
    Public Property Venta24 As Decimal
    Public Property Venta25 As Decimal
    Public Property Venta26 As Decimal
    Public Property Venta27 As Decimal
    Public Property Venta28 As Decimal
    Public Property Venta29 As Decimal
    Public Property Venta30 As Decimal
    Public Property Venta31 As Decimal
    Public Property Moneda As Moneda

End Class
